# Generated by Django 4.2.11 on 2024-03-23 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('un', models.IntegerField(verbose_name='United Nations Code')),
                ('area', models.IntegerField()),
                ('region', models.IntegerField(verbose_name='Region Code')),
                ('subregion', models.IntegerField(verbose_name='Sub-Region Code')),
                ('pop2005', models.IntegerField(verbose_name='Population 2005')),
                ('name', models.CharField(max_length=50)),
                ('fips', models.CharField(max_length=2, null=True, verbose_name='FIPS Code')),
                ('iso2', models.CharField(max_length=2, verbose_name='2 Digit ISO')),
                ('iso3', models.CharField(max_length=3, verbose_name='3 Digit ISO')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HouseCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HouseElection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('election_type', models.CharField(choices=[('federal', 'Regular'), ('equestrian', 'Equestrian')], max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('abbreviation', models.CharField(blank=True, max_length=15, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Parties',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreferenceRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.houseelection')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('state', models.CharField(choices=[('act', 'Australian Capital Territory'), ('nsw', 'New South Wales'), ('nt', 'Northern Territory'), ('qld', 'Queensland'), ('sa', 'South Australia'), ('tasmania', 'Tasmania'), ('victoria', 'Victoria'), ('wa', 'Western Australia')], max_length=9)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('elections', models.ManyToManyField(blank=True, to='jacobsladder.houseelection')),
                ('location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jacobsladder.geography')),
            ],
        ),
        migrations.CreateModel(
            name='SenateCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SenateElection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('act', 'Australian Capital Territory'), ('nsw', 'New South Wales'), ('nt', 'Northern Territory'), ('qld', 'Queensland'), ('sa', 'South Australia'), ('tasmania', 'Tasmania'), ('victoria', 'Victoria'), ('wa', 'Western Australia')], max_length=9)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoteTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.preferenceround')),
                ('source_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_via', to='jacobsladder.housecandidate')),
                ('target_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_via', to='jacobsladder.housecandidate')),
            ],
        ),
        migrations.CreateModel(
            name='VoteTally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_votes', models.IntegerField()),
                ('tcp_votes', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.housecandidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.houseelection')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.seat')),
            ],
            options={
                'verbose_name_plural': 'Vote Tallies',
            },
        ),
        migrations.CreateModel(
            name='VoteDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('vote_count_change', models.IntegerField()),
                ('reason', models.CharField(max_length=127)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.senatecandidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.senateelection')),
                ('source_tally', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.votetally')),
            ],
        ),
        migrations.CreateModel(
            name='SenateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('abbreviation', models.CharField(blank=True, max_length=15, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.senateelection')),
            ],
        ),
        migrations.AddField(
            model_name='senatecandidate',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jacobsladder.senategroup'),
        ),
        migrations.AddField(
            model_name='senatecandidate',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.person'),
        ),
        migrations.CreateModel(
            name='SeatChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=127)),
                ('date_of_change', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('from_seat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_via', to='jacobsladder.seat')),
                ('to_seat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_via', to='jacobsladder.seat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Representation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.houseelection')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.party')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.person')),
            ],
        ),
        migrations.AddField(
            model_name='preferenceround',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.seat'),
        ),
        migrations.AddField(
            model_name='person',
            name='party',
            field=models.ManyToManyField(through='jacobsladder.Representation', to='jacobsladder.party'),
        ),
        migrations.CreateModel(
            name='PartyAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('elections', models.ManyToManyField(blank=True, to='jacobsladder.houseelection')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.party')),
            ],
            options={
                'verbose_name_plural': 'Party Aliases',
            },
        ),
        migrations.AddField(
            model_name='housecandidate',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.person'),
        ),
        migrations.AddField(
            model_name='housecandidate',
            name='seat',
            field=models.ManyToManyField(through='jacobsladder.Contention', to='jacobsladder.seat'),
        ),
        migrations.AddField(
            model_name='contention',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.housecandidate'),
        ),
        migrations.AddField(
            model_name='contention',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.houseelection'),
        ),
        migrations.AddField(
            model_name='contention',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.seat'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.booth')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.houseelection')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.seat')),
            ],
        ),
        migrations.CreateModel(
            name='CandidatePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes_received', models.IntegerField()),
                ('votes_transferred', models.IntegerField()),
                ('votes_remaining', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.housecandidate')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.preferenceround')),
            ],
        ),
        migrations.CreateModel(
            name='BoothChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=127)),
                ('date_of_change', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('from_booth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_via', to='jacobsladder.booth')),
                ('to_booth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_via', to='jacobsladder.booth')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='booth',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jacobsladder.geography'),
        ),
        migrations.AddField(
            model_name='booth',
            name='seats',
            field=models.ManyToManyField(blank=True, through='jacobsladder.Collection', to='jacobsladder.houseelection'),
        ),
    ]
