# Generated by Django 4.2.11 on 2024-04-30 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jacobsladder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.senateelection')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.party')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.person')),
            ],
        ),
        migrations.AddConstraint(
            model_name='selection',
            constraint=models.UniqueConstraint(fields=('person', 'party', 'election'), name='selection_person_party_election'),
        ),
    ]
