# Generated by Django 4.2.11 on 2024-04-05 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jacobsladder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votetally',
            name='seat',
        ),
        migrations.AddField(
            model_name='booth',
            name='name',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='votetally',
            name='booth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.booth'),
        ),
    ]
