# Generated by Django 4.2.11 on 2024-04-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jacobsladder', '0002_remove_votetally_seat_booth_name_votetally_booth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='name',
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
