# Generated by Django 4.2.11 on 2024-04-30 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jacobsladder', '0002_selection_selection_selection_person_party_election'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='selection',
            name='selection_person_party_election',
        ),
        migrations.AlterField(
            model_name='selection',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jacobsladder.party'),
        ),
        migrations.AddConstraint(
            model_name='selection',
            constraint=models.UniqueConstraint(fields=('person', 'election'), name='selection_person_election'),
        ),
    ]
