# Generated by Django 4.2.11 on 2024-04-30 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jacobsladder', '0003_remove_selection_selection_person_party_election_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lighthouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('act', 'Australian Capital Territory'), ('nsw', 'New South Wales'), ('nt', 'Northern Territory'), ('qld', 'Queensland'), ('sa', 'South Australia'), ('tas', 'Tasmania'), ('vic', 'Victoria'), ('wa', 'Western Australia')], max_length=9)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=63, unique=True)),
                ('elections', models.ManyToManyField(blank=True, to='jacobsladder.senateelection')),
                ('location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jacobsladder.geography')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
