# Generated by Django 4.2.11 on 2024-04-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jacobsladder', '0003_alter_seat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='division_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seat',
            name='enrollment',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seat',
            name='state',
            field=models.CharField(choices=[('act', 'Australian Capital Territory'), ('nsw', 'New South Wales'), ('nt', 'Northern Territory'), ('qld', 'Queensland'), ('sa', 'South Australia'), ('tas', 'Tasmania'), ('vic', 'Victoria'), ('wa', 'Western Australia')], max_length=9),
        ),
        migrations.AlterField(
            model_name='senateelection',
            name='state',
            field=models.CharField(choices=[('act', 'Australian Capital Territory'), ('nsw', 'New South Wales'), ('nt', 'Northern Territory'), ('qld', 'Queensland'), ('sa', 'South Australia'), ('tas', 'Tasmania'), ('vic', 'Victoria'), ('wa', 'Western Australia')], max_length=9),
        ),
    ]
