# Generated by Django 4.2.11 on 2024-04-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jacobsladder', '0004_seat_division_id_seat_enrollment_alter_seat_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='division_id',
            new_name='division_aec_code',
        ),
        migrations.AddField(
            model_name='booth',
            name='polling_place_aec_code',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contention',
            name='ballot_position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contention',
            name='candidate_aec_code',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='last_known_codepartyyear',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='other_names',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=31),
        ),
    ]
