# Generated by Django 4.2.11 on 2024-04-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jacobsladder', '0005_rename_division_id_seat_division_aec_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votetally',
            name='tcp_votes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
