# Generated by Django 4.2.11 on 2024-04-19 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jacobsladder', '0006_alter_votetally_tcp_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatepreference',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.housecandidate'),
        ),
        migrations.AddField(
            model_name='candidatepreference',
            name='source_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_preference', to='jacobsladder.housecandidate'),
        ),
        migrations.AlterField(
            model_name='candidatepreference',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_preference', to='jacobsladder.housecandidate'),
        ),
    ]
