# Generated by Django 4.2.11 on 2024-04-30 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jacobsladder', '0006_lighthousecode_lighthousecode_number_and_lighthouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=63, null=True)),
                ('lighthouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.lighthouse')),
                ('location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jacobsladder.geography')),
            ],
        ),
        migrations.AddConstraint(
            model_name='floor',
            constraint=models.UniqueConstraint(fields=('name', 'lighthouse'), name='name_and_lighthouse'),
        ),
    ]
