# Generated by Django 4.2.11 on 2024-04-19 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jacobsladder', '0007_candidatepreference_seat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatepreference',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.seat'),
        ),
    ]
