# Generated by Django 4.2.11 on 2024-04-19 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jacobsladder', '0008_alter_candidatepreference_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatepreference',
            name='election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.houseelection'),
        ),
    ]
