# Generated by Django 4.2.11 on 2024-05-01 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jacobsladder', '0009_stand_alter_senategroup_abbreviation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_votes', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('act', 'Australian Capital Territory'), ('nsw', 'New South Wales'), ('nt', 'Northern Territory'), ('qld', 'Queensland'), ('sa', 'South Australia'), ('tas', 'Tasmania'), ('vic', 'Victoria'), ('wa', 'Western Australia')], max_length=9)),
                ('tpp_votes', models.IntegerField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.senatecandidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.senateelection')),
                ('floor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.floor')),
                ('lighthouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.lighthouse')),
            ],
        ),
        migrations.AddConstraint(
            model_name='votestack',
            constraint=models.UniqueConstraint(fields=('floor', 'election', 'candidate'), name='floor_election_and_candidate'),
        ),
    ]
