# Generated by Django 4.2.11 on 2024-04-19 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jacobsladder', '0009_candidatepreference_election'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='enrollment',
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_enrolled', models.PositiveIntegerField(default=0)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.houseelection')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.seat')),
            ],
        ),
    ]
