# Generated by Django 4.2.11 on 2024-05-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jacobsladder', '0010_votestack_votestack_floor_election_and_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(fields=('abbreviation', 'name'), name='abbreviation_and_name'),
        ),
    ]
