# Generated by Django 4.2.11 on 2024-04-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jacobsladder', '0010_remove_seat_enrollment_enrollment'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('name', 'division_aec_code'), name='unique_name_plus_code'),
        ),
    ]
