# Generated by Django 4.2.11 on 2024-04-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jacobsladder', '0011_seat_unique_name_plus_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='name',
            field=models.CharField(max_length=63),
        ),
    ]
