# Generated by Django 4.2.11 on 2024-05-01 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jacobsladder', '0011_alter_party_name_party_abbreviation_and_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('act', 'Australian Capital Territory'), ('nsw', 'New South Wales'), ('nt', 'Northern Territory'), ('qld', 'Queensland'), ('sa', 'South Australia'), ('tas', 'Tasmania'), ('vic', 'Victoria'), ('wa', 'Western Australia')], max_length=9)),
                ('formal_papers', models.PositiveIntegerField()),
                ('quota', models.PositiveIntegerField()),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.senateelection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
