# Generated by Django 4.2.11 on 2024-04-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jacobsladder', '0012_alter_seat_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='candidatepreference',
            constraint=models.UniqueConstraint(fields=('candidate', 'round', 'seat', 'election'), name='unique_combination_of_candidate_round_seat_election'),
        ),
    ]
