# Generated by Django 4.2.11 on 2024-04-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jacobsladder', '0013_candidatepreference_unique_combination_of_candidate_round_seat_election'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatepreference',
            name='votes_remaining',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
