# Generated by Django 4.2.11 on 2024-05-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jacobsladder', '0013_pool_pool_state_and_election'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='vacancies',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
