# Generated by Django 4.2.11 on 2024-04-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jacobsladder', '0014_alter_candidatepreference_votes_remaining'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='seat',
            name='unique_name_plus_code',
        ),
        migrations.AddConstraint(
            model_name='booth',
            constraint=models.UniqueConstraint(fields=('name', 'polling_place_aec_code'), name='unique_name_plus_code'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('booth', 'seat', 'election'), name='unique_combination_of_booth_seat_election'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('seat', 'election'), name='unique_seat_for_election'),
        ),
        migrations.AddConstraint(
            model_name='preferenceround',
            constraint=models.UniqueConstraint(fields=('seat', 'election', 'round_number'), name='unique_combination_of_seat_election_round_number'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('name', 'division_aec_code'), name='unique_seat_name_plus_code'),
        ),
    ]
