# Generated by Django 4.2.11 on 2024-05-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jacobsladder', '0016_alter_candidatepreference_source_candidate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senatepreference',
            name='papers',
            field=models.IntegerField(),
        ),
    ]
