# Generated by Django 4.2.11 on 2024-05-05 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jacobsladder', '0017_alter_senatepreference_papers'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseAlliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.houseelection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetaParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SenateAlliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.senateelection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='votetransfer',
            name='round',
        ),
        migrations.RemoveField(
            model_name='votetransfer',
            name='source_candidate',
        ),
        migrations.RemoveField(
            model_name='votetransfer',
            name='target_candidate',
        ),
        migrations.DeleteModel(
            name='VoteDistribution',
        ),
        migrations.DeleteModel(
            name='VoteTransfer',
        ),
        migrations.AddField(
            model_name='contention',
            name='alliance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jacobsladder.housealliance'),
        ),
        migrations.AddField(
            model_name='party',
            name='meta_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jacobsladder.metaparty'),
        ),
        migrations.AddField(
            model_name='stand',
            name='alliance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jacobsladder.senatealliance'),
        ),
    ]
