# Generated by Django 4.2.11 on 2024-05-16 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jacobsladder', '0019_alter_houseelection_election_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='votetally',
            name='unique_combination_of_booth_election_and_candidate',
        ),
        migrations.AddField(
            model_name='votetally',
            name='absent_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='votetally',
            name='aec_ordinary',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='votetally',
            name='aec_swing',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='votetally',
            name='aec_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='votetally',
            name='bypass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jacobsladder.seat'),
        ),
        migrations.AddField(
            model_name='votetally',
            name='declaration_pre_poll_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='votetally',
            name='postal_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='votetally',
            name='provisional_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='votetally',
            name='primary_votes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='votetally',
            constraint=models.UniqueConstraint(fields=('booth', 'bypass', 'election', 'candidate'), name='booth_bypass_election_candidate'),
        ),
    ]
